version: "3"
services:
  store:
    build: ./store
    ports:
      - 3306:3306
    volumes:
      - "dbdata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: psystemdb
      MYSQL_USER: psystemapi
      MYSQL_PASSWORD: 12344

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  api:
    build: ./api
    ports:
      - 8082:80
    depends_on:
      - store
    environment:
      MYSQL_HOST: store
      MYSQL_DATABASE: psystemdb
      MYSQL_USER: psystemapi
      MYSQL_PASSWORD: 12344
      API_ENDPOINT: http://localhost:8082/web

for passing env varibile at build stage, see note at https://docs.docker.com/compose/compose-file/#environment
  frontend:
    build:
      context: ./frontend
      args:
        - API_ENDPOINT=http://localhost:8082/web
    ports:
      - 8080:80
    depends_on:
      - api

volumes:
  dbdata: