version: "3"
services:
  store:
    build: ./store
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  api:
    build: ./api
    ports:
      - 8082:80
    depends_on:
      - store
    environment:
      - MYSQL_HOST=store
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

# for passing env varibile at build stage, see note at https://docs.docker.com/compose/compose-file/#environment
  frontend:
    build:
      context: ./frontend
      args:
        - API_ENDPOINT=http://localhost:8082
    ports:
      - 8080:80
    depends_on:
      - api

